[[dependency]]
package = "github.com/buckaroo-pm/boost-any"
version = "1.55.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
version = "1.55.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.55.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "1.55.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
version = "1.55.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
version = "1.55.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
version = "1.55.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
version = "1.55.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
version = "1.55.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
version = "1.55.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "1.55.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
version = "1.55.0"