manifest = "6f1aed768e72447497e3f74bb0e850a2864bdf7668fa49acd8183c91ad7888c7"

[[dependency]]
package = "github.com/buckaroo-pm/boost-any"
target = "//:any"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
target = "//:function"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
target = "//:tuple"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-any"]
versions = [ "1.40.0" ]
revision = "d890c241bc8e74dbf3b299f7880c79ba734c95fb"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.40.0" ]
revision = "8482bef2c8cbbd2165a304e3362d911e00a08064"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.40.0" ]
revision = "3a9079edc4b058e42495a36ca7cbdc20675a64e3"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.40.0" ]
revision = "e71d7a0f72b577ee4f5dd702dfed18709ed72681"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.40.0" ]
revision = "e3601e2e3bc857f88c892ca4c134020099a4c051"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.40.0" ]
revision = "8bda4592d2b32baf52ed50ed5809501a11beee71"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.40.0" ]
revision = "21a147d53ace9c3bf16002e8eaf3eeeb1056dc4f"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.40.0" ]
revision = "3cbd509d83445c0ef09b729aa146c47f827b7386"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.40.0" ]
revision = "85f257f138e6eae7e61906452db3ed2158f6def9"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.40.0" ]
revision = "216d40fae0850d3287ab60bf1f9e9fdae8b66e5d"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.40.0" ]
revision = "bd7e994a6782500e1b4fb1ccf7b92a3aafef3bc4"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.40.0" ]
revision = "dc550518155c7bcddd980d414e4e20735e2ff565"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.40.0" ]
revision = "e329534f2f2d9fb213302ebe6a5688634ff069c1"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.40.0" ]
revision = "b459dd5be9de4e4969097056bbac57a36112fa76"
