manifest = "1ff8456c6d89580176be6e0e5ac11a26134496a863be171b77d29c3865661093"

[[dependency]]
package = "github.com/buckaroo-pm/boost-any"
target = "//:any"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
target = "//:function"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
target = "//:tuple"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-any"]
versions = [ "1.48.0" ]
revision = "3d72cbfa046e9f976b5019d6b9eb11b10265c4ec"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.48.0" ]
revision = "114bca7424a5da83e30dc8289569039c32a96a27"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.48.0" ]
revision = "f2a3d12da550aca457374033ba38554ccb3b06df"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.48.0" ]
revision = "4298a8c284c634b14e57645296da02636908c57d"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.48.0" ]
revision = "091a74df0877ca3bacd25f50ebdfa23a63dcf4cf"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.48.0" ]
revision = "b9ccc9250df2e0328463466c3855dae33a1b35c3"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.48.0" ]
revision = "b1c8451dcbf65e335bb429f75279e3346d67a90f"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.48.0" ]
revision = "26a10cdeb43f4b55ad9f8897c89fb289b8c17d84"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.48.0" ]
revision = "5c11da0c08b834b0ad4a20419c839d04b0b4e625"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.48.0" ]
revision = "8e7647a0fcf5d26c7b5ac6b479d4a656df79ba2b"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.48.0" ]
revision = "4c1501769e93fc95215fcf9c60d74f8fd217f3ab"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.48.0" ]
revision = "e96ba8537c2fc4db905d0edb640d9f9fbf6c275d"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.48.0" ]
revision = "27120861a6c715ce0e09c2e9ca6456afef5eb5c0"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.48.0" ]
revision = "b754127b1ce914967306ff09411e8922bb1a7931"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.48.0" ]
revision = "ee9cacf3d7ecdef21f84300597bf92739eca2530"
