manifest = "4d9cd591e84ff3f02584194f0a232374d78d33f688d68234e85e3d419d20135c"

[[dependency]]
package = "github.com/buckaroo-pm/boost-any"
target = "//:any"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
target = "//:function"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
target = "//:tuple"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-any"]
versions = [ "1.41.0" ]
revision = "637dac8160fd3300f7aec07927cf0c61b280d0a3"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.41.0" ]
revision = "8393eee46e7ad152b5826f4474d75daf963cd624"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.41.0" ]
revision = "c32805df725494aca225f78f2d64b24bdf99e56a"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.41.0" ]
revision = "3dd65e69f2a9ed5bfc98d36329c9e832a650cf2b"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.41.0" ]
revision = "36941a2b4fea55e81b76dabc8fdc4834dc729a4d"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.41.0" ]
revision = "820cdd0df618d97b19e6583507b03320724cc35f"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.41.0" ]
revision = "0a555607f1281827ffdcd51cf77c03bdbdb43277"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.41.0" ]
revision = "37f6440c2fea2aa756087b8f7c8274c9ee4081a6"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.41.0" ]
revision = "c848776c45974808d87763367162d9ab445c323e"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.41.0" ]
revision = "adf0042465cd0471607047f1472c937fb0e4aed6"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.41.0" ]
revision = "27473651c329bf6c2218c6899279776ffb3783a7"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.41.0" ]
revision = "74f8c1a68d235ce4c4b215c3b409c406942fc2b0"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.41.0" ]
revision = "3c64dc1b29e86b9b83d3448cf78fb1fd357a3d9d"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.41.0" ]
revision = "3624b627abc4776a3499ce10b7fcaa0c4821346e"
