manifest = "3ed2b7858e9525e29e990eb05d47cfca9a917cbce65e46b3cb46bfda72f47f42"

[[dependency]]
package = "github.com/buckaroo-pm/boost-any"
target = "//:any"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
target = "//:function"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
target = "//:tuple"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-any"]
versions = [ "1.47.0" ]
revision = "42df8e3a2dd81ab701f6d8b4fe851cdd8f039ce8"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.47.0" ]
revision = "27e7a1ca1eba2d080c3520e9e9cd509052f0588b"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.47.0" ]
revision = "f6585b1993077d3de95ebcf766e3346b8aebb490"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.47.0" ]
revision = "f39e5671b0d09010441b6549031deb68b7c75d44"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.47.0" ]
revision = "74825bfedfa6d344e420758b75211589fbad19bb"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.47.0" ]
revision = "32eb9a6b12b5b39a766f8e722630b1dcdb2b385b"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.47.0" ]
revision = "c0cbf0c7044a075d52de530becacbe107da297a6"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.47.0" ]
revision = "cb8e48d0792e765a836b860ca4cd369d614afb36"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.47.0" ]
revision = "5b15e9b0092d3fccfb29c8baa352116f4c4575bd"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.47.0" ]
revision = "a10aeaf3d41bcfb604ae3d55df0842775df7646c"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.47.0" ]
revision = "b17cd5bfcc8eb6cde44203dde758b9776586a75a"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.47.0" ]
revision = "96ec3111a19b69c4665ccf510e9cc27f31717419"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.47.0" ]
revision = "4c0ca7efafeb92fef2e725bcdebebc4173757633"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.47.0" ]
revision = "f819363b8527a9d718c3f170e44d3a54ed618749"
