manifest = "507744195224bba373c1d51372a1c255d7246c7ccb15dae8bf86196a76ae6975"

[[dependency]]
package = "github.com/buckaroo-pm/boost-any"
target = "//:any"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
target = "//:function"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
target = "//:tuple"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-any"]
versions = [ "1.55.0" ]
revision = "44a36cd40b225543c954f1e16b3527bd0ccf53e5"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.55.0" ]
revision = "6894aca9c2c2e8a5f192f85e2258cc17e1718b3c"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.55.0" ]
revision = "892598f066f15a4b8352bbd6b5f2b1a90e12e6fc"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.55.0" ]
revision = "8fe65abe2334e0d84c2cba4c768ec2f2360b33e1"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.55.0" ]
revision = "cd70d4604a65f00b027e05f89940c57e969f9881"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.55.0" ]
revision = "6e1f8747229dfb5a62a5c55671f82b9c671db417"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.55.0" ]
revision = "9feb51ac8747b52cee096937fc17567131b611f3"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.55.0" ]
revision = "17efc70a43f3d9379475b9637855b2be09da3bcd"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.55.0" ]
revision = "8dcbb4d4610e05a948704c47898a34c4fee827cb"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "1.55.0" ]
revision = "a22fdd340392a0cc4d870b6fbbd49ce1d1c44e88"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.55.0" ]
revision = "a41bc5546421204bda9a1572a75474b7197559b2"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.55.0" ]
revision = "aa39a2eb459c84e93949303e04c387d67d0a7b60"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.55.0" ]
revision = "e14d6eb7ed4f944d0c0bb723e4732c5ea80d0d1d"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.55.0" ]
revision = "94bb5d3f560204421d4018b75d25dd5381325082"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.55.0" ]
revision = "5bc29dc8cdbe07565bdbbcdb2e70824e51eabf26"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.55.0" ]
revision = "59b48f8ac824d7985183ffb3c3174c8caebfef20"
